### ISSUE TITLE
Question for Synology use

### ISSUE THREAD

**Issue by Martinnygaard** [matt8707/hass-config#31]
Hi,

This is not an issue at all, but rather a question:

I am also running HA from a docker environment on my DS920+, but I am having big problems with the docker version being only v18.xx while HA requires v19 to work.
Recently that issue started to break integrations like ESPHome, Grafana on my installation.

Have you done anything to fix this issue on your side? Or is it not a problem for you?

Br
Martin

**Comment by rosscullen** [comment]
Hi Martin,

I'm in a similar position. Having read the recent Home Assistant Github issue at https://github.com/home-assistant/supervisor/issues/2514 they are unable to support Synology users. I assume this is primarily down to the fact that Synology DSM 6.* still uses v18. As with the upcoming DSM 7, there has been nothing concrete on the version of Docker that will be available.

I assume like I that you are using the excellent hassio package for Synology from Fredrik Erlandsson which has since been discontinued. See https://community.home-assistant.io/t/home-assistant-supervised-previously-known-as-hass-io-on-synology-dsm-as-native-package-not-supported-or-working-atm/125559

Personally I  am left with little choice but to run HASSIO on my Synology as a virtual machine. in the very near future (waiting on extra RAM for Synology). Beardedtinker has an excellent video explaining it at https://www.youtube.com/watch?v=MSDoCXrlr_Q

Hope this helps.
R

**Comment by matt8707** [comment]
Sorry for the late response, been away from hass..

I'm using "Container" which is 100% supported https://www.home-assistant.io/installation/#compare-installation-methods

If you look at the list you don't get Supervisor, Add-ons, Snapshots, Managed OS. So to replace that functionality

**Supervisor**: In my repo there's rest sensors for home assistant releases
**Add-ons**: Are just docker containers, usually update them with watchtower
**Snapshots**: I use [Hyper Backup](https://www.synology.com/sv-se/dsm/feature/hyper_backup) to google drive
**Managed OS**: Obviously DiskStation Manager

I do not feel like I lose out on any features, hope that helps!

![synology](https://user-images.githubusercontent.com/36163594/120798472-b24d0100-c53d-11eb-9881-86a6e7fff557.png)
