### ISSUE TITLE
Popup-Style

### ISSUE THREAD

**Issue by georgbachmann** [matt8707/hass-config#4]
One more question. I tried the browser_mod plugin but my style is different to yours (and I LOVE dark UIs ;) ) I guess this is the default theme that I'd need to use, right? Can you tell me which one you use?

Also... the Button for closing the popup. In your sample-screenshot it aligns where it should. For me it makes this strange border around everything and it's just totally off?!? Do you have an idea what the problem could be?

And while I am here asking :) The bar-card icon and text are first: wrong colo, second miss-aligned and third show those up and down triangles. Do you know how to fix those as well?

Oh.. and `sensor.home_assistant_v2_db`... I couldn't find any more info on that one in your config files?!?

Thank you so much for sharing your config! I absolutely love it!

<img width="1414" alt="Bildschirmfoto 2020-01-26 um 20 35 18" src="https://user-images.githubusercontent.com/893113/73140637-6b164c80-407b-11ea-9f52-143e4b1691c0.png">

**Comment by matt8707** [comment]
- I use this the [themes.yaml](https://github.com/matt8707/hass-config/blob/master/themes.yaml) in the root of the config. You have to enable it https://www.home-assistant.io/integrations/frontend/

- I think it's because you removed the tablet card in the middle. You could try to [decrease the padding here](https://github.com/matt8707/hass-config/blob/master/ui-lovelace.yaml#L713).

- I don't know, just nudge the numbers in the css. The triangles shows if the cpu goes up or down.

- You can search repositories. https://github.com/matt8707/hass-config/blob/master/configuration.yaml#L494

Hope that helps!
