### ISSUE TITLE
Licence, Terms & Conditions

### ISSUE THREAD

**Issue by hofq** [matt8707/hass-config#47]
Hey Matt, I love the Project!

I am Setting it up myself, but i was wondering under which licence you handle it, since on the Github is no Licence found.

Thanks :)

**Comment by matt8707** [comment]
Hi! I have not even thought about it. Do you know which license that would fit here? 

I'm just sharing my configuration, you can do anything you want for personal use.

**Comment by stelterlab** [comment]
Hi! Take a look at https://choosealicense.com/ - that could be useful.

**Comment by Kippenhof** [comment]
Normal Open Source Licences would be [MIT ](https://tldrlegal.com/license/mit-license)or[ Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) but these include Commertial use.

You also have Licences like [AGPL v3](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)) that force you to disclose your souce, but because many people change stuff in you conf's for local use (including me) it wouldn't be the best option.

from these Options i would go with Apache 2.0 , but i recommend you to take a look at https://choosealicense.com/  like @stelterlab said.

**Comment by pmontp19** [comment]
In fact, if you don't specifically include a license the code is under copyright by default. It's always a good thing to do include a license within your projects. 

As @stelterlab shared, in https://choosealicense.com/no-permission/ there is more information about this specific case.
